### ISSUE TITLE
Problem opening local Maven archetypes

### ISSUE THREAD

**Issue by wirepatch** [dmarks2/maven-archetypes-catalog-plugin#6] opened 2017-06-02 06:02 UTC
**Description: The maven-archetypes-catalog-plugin fails when opening local archetypes not available on public repositories.**

System: Ubuntu/Linux + latest Intellij idea 2017.1.3 Build #IU-171.4424.56, built on May 12, 2017 ultimate version.

Details: I've configured the plugin to use our (publicly available) Maven archtype catalog [https://maven.mi.hdm-stuttgart.de/archetype-catalog.xml](https://maven.mi.hdm-stuttgart.de/archetype-catalog.xml).

Our four archtypes are on offer to be selected when creating a new Maven project in idea. But actually creating the beast using e.g. **mi-maven-archetype-quickstart** fails with:

`/usr/lib/jvm/java-8-oracle/bin/java -Dmaven.multiModuleProjectDirectory=/tmp/archetypetmp -Dmaven.home=/usr/share/idea-IU-171.4424.56/plugins/maven/lib/maven3 -Dclassworlds.conf=/usr/share/idea-IU-171.4424.56/plugins/maven/lib/maven3/bin/m2.conf -Dfile.encoding=UTF-8 -classpath /usr/share/idea-IU-171.4424.56/plugins/maven/lib/maven3/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2017.1.3 -DinteractiveMode=false -DgroupId=qq -DartifactId=qq -Dversion=1.0-SNAPSHOT -DarchetypeGroupId=de.hdm-stuttgart.mi -DarchetypeArtifactId=mi-maven-archetype-quickstart -DarchetypeVersion=1.1 -DarchetypeRepository=https://maven.mi.hdm-stuttgart.de/Archetypes org.apache.maven.plugins:maven-archetype-plugin:RELEASE:generate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.0.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.0.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] --- maven-archetype-plugin:3.0.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repsoitory with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
Downloading: https://repo.maven.apache.org/maven2/de/hdm-stuttgart/mi/mi-maven-archetype-quickstart/1.1/mi-maven-archetype-quickstart-1.1.pom
[WARNING] The POM for de.hdm-stuttgart.mi:mi-maven-archetype-quickstart:jar:1.1 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/de/hdm-stuttgart/mi/mi-maven-archetype-quickstart/1.1/mi-maven-archetype-quickstart-1.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.199 s
[INFO] Finished at: 2017-06-02T07:27:48+02:00
[INFO] Final Memory: 15M/197M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (de.hdm-stuttgart.mi:mi-maven-archetype-quickstart:1.1) -> [Help 1]...`

As the logs show the underlying Maven process tries to fetch e.g. https://repo.maven.apache.org/maven2/de/hdm-stuttgart/mi/mi-maven-archetype-quickstart/1.1/mi-maven-archetype-quickstart-1.1.pom rather than https://maven.mi.hdm-stuttgart.de/Archetypes/de/hdm-stuttgart/mi/mi-maven-archetype-quickstart/1.1/mi-maven-archetype-quickstart-1.1.pom as being defined in the configured archetype catalog.

Apparently Maven no longer honors the -DarchetypeRepository=https://maven.mi.hdm-stuttgart.de/Archetypes  switch as being inferred by [https://stackoverflow.com/questions/42278422/maven-archetypegenerate-plugin-3-0-how-to-specify-remote-repository](https://stackoverflow.com/questions/42278422/maven-archetypegenerate-plugin-3-0-how-to-specify-remote-repository).

So far the only "fix" seems to be configuring https://maven.mi.hdm-stuttgart.de/Archetypes in ~/.m2/settings.xml manually.

BTW: Configuring the catalog in question for Eclipse as being outlined in https://freedocs.mi.hdm-stuttgart.de/sd1SectUsingMavenEclipse.html still works like a charm.

Edit: The following ~/.m2/settings.xml provides a workaroud:

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <profiles>
    <profile>
      <id>dev</id>
        <repositories>
            <repository>
              <id>archetype</id>
              <url>https://maven.mi.hdm-stuttgart.de/Archetypes</url>
              <releases><enabled>true</enabled></releases>
              <snapshots><enabled>true</enabled></snapshots>
            </repository>
        </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>dev</activeProfile>
  </activeProfiles>
</settings>
```

**Comment by dmarks2** [comment] 2017-06-02 08:37
The problem behind this is a Maven problem and not a problem of the IntelliJ IDEA Plugin.

The maven-archetype-plugin removed support for the parameter -DarchetypeRepository from Version 3.0.0  onwards. 

So your "workaround" is the solution for this problem. This is also mentioned in the issue tracker for the maven-archetype-plugin, e.g. https://issues.apache.org/jira/browse/ARCHETYPE-519.

I close this issue as the root cause is in the maven-archetype-plugin and not in my IntelliJ IDEA Plugin.

**Comment by dmarks2** [comment] 2017-06-05 14:07
I could image an option to "skip" the repository definition. That way the maven command will not contain any -DarchetypeRepository parameter. In this case the repository settings from your settings.xml will be used.

**Comment by wirepatch** [comment] 2017-06-05 15:45
Yes, that sounds good: Currently Maven tries to locate the archetype on a public repository first before trying the one being configured in settings.xml.
In addition I suggest a prominent hint to a suitable minimalistic settings.xml example. It took me some time before getting mine working.

**Comment by dmarks2** [comment] 2017-06-05 17:19
Feature is implemented. New version is waiting for approval by JetBrains.

**Closed as completed by dmarks2** 2017-06-05 17:19 UTC
Labels: enhancement
