### ISSUE TITLE
Warning in IDEA console when creating project from Archetype: maven-archetype-site

### ISSUE THREAD

**Issue by stefango** [dmarks2/maven-archetypes-catalog-plugin#11] opened 2020-03-22 15:25 UTC
Hi, can you do me a favor?
I got a Warning in IDEA console when creating a project from Archetype: maven-archetype-site.
The console warning is：
```
Archetype not found in any catalog. Falling back to central repository.
Add a repsoitory with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
```

**Comment by dmarks2** [comment] 2020-03-23 16:08
I think this is a warning from maven and not generated by the IntellIJ IDEA plugin. 

I will check if there is any side effect of my IntelliJ IDEA plugin here...

**Comment by dmarks2** [comment] 2020-03-24 17:36
The problem is a duplicate of https://github.com/dmarks2/maven-archetypes-catalog-plugin/issues/6.

The problem behind it is caused by maven and not by my IntelliJ IDEA plugin. Depending on your maven version please check if the option "Skip Repository Definition" in my plugin can help you.

**Closed as completed by dmarks2** 2020-03-24 17:36 UTC
Labels: duplicate
